apiVersion: v1
appVersion: "1.0"
description: A Senzing environment for console access
home: http://senzing.com
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - senzing
 - console
name: senzing-console
sources:
 - https://github.com/Senzing/docker-senzing-console
version: 1.0.0
